server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true